### PR TITLE
fix routing for quiz pages

### LINKED ISSUE #46: Question 1 Page:  Back and next button
image

### PR DESCRIPTION
**Pull request by Raymond0T**
#### What is the purpose of your change?
-Changes to routing for quiz buttons(backward, forward) fixes #46 and #41 

#### What areas of the application does this change impact? (changes API, folder structure, etc)
-quiz component

#### What features/fixes are deferred/not handled in this PR?
-

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

### CODE REVIEW

File: tmt-app/src/Components/Quiz.jsx [hunk 1]
```diff
@@ -21,14 +24,19 @@ function Quiz() {
     <Container sx={{ width: '100%' }}>
       <QuizStepper />
       <Text step={step} />
-      <Grid container justifyContent={{ xs: 'center', lg: 'flex-start' }}>
-        {data.map((item) => (
-          <Grid item key={item.title}>
-            <QuestionCard item={item} />
+      {step !== 'receipt' && (
```
Comment (michachan) [inline tmt-app/src/Components/Quiz.jsx:27]: Ideally this would be a [....].includes(step)

**Review by michachan — APPROVED** [review]
