### PR TITLE
add button, change data, and fix icon for quiz

### LINKED ISSUE #121: Add button, change data, and fix icon for quiz
Ticket for @Raymond0T

### PR DESCRIPTION
**Pull request by Raymond0T**
#### What is the purpose of your change?
-add button, change data, and fix icon for quiz (fixes #121)

#### What areas of the application does this change impact? (changes API, folder structure, etc)
-data file, images folder, and quiz component

#### What features/fixes are deferred/not handled in this PR?
-

#### Screenshot/link:
https://deploy-preview-120--pick-a-major.netlify.app/quiz/classes
image

## Checklist
- [ ] Adds unit tests
- [ ] Has a work item linked to the PR

### CODE REVIEW

File: tmt-app/src/Components/Quiz.jsx [hunk 1]
```diff
@@ -29,6 +28,27 @@ function Quiz() {
           </Grid>
         ))}
       </Grid>
+      <Link
```
Comment (jwu910) [inline tmt-app/src/Components/Quiz.jsx:31]: We need some layout for this button. What does the desktop and mobile positions look like for this?

Reviewing on mobile is pretty unusable still

File: tmt-app/src/Components/Quiz.jsx [hunk 2]
```diff
@@ -29,6 +28,27 @@ function Quiz() {
...
+        to="/quiz/skills"
+      >
+        <PrimaryBtn
+          sx={{
+            backgroundColor: 'Matcha.main',
+            '&.MuiButtonBase-root': {
+              padding: {
+                xs: '1rem 2.5rem',
+                xl: '1rem 3.25rem',
+              },
```
Comment (jwu910) [inline tmt-app/src/Components/Quiz.jsx:45]: Can we not just add padding directly here? Why do we need to override with the button root class?

File: tmt-app/src/Components/Quiz.jsx [hunk 3]
```diff
@@ -29,6 +28,27 @@ function Quiz() {
...
         ))}
       </Grid>
+      <Link
+        sx={{ color: 'Boba.main' }}
+        underline="none"
+        aria-label="Learn more about other different majors"
+        component={RouterLink}
+        to="/quiz/skills"
+      >
+        <PrimaryBtn
```
Comment (jwu910) [inline tmt-app/src/Components/Quiz.jsx:38]: Have we also played with button size variants? Rather than manual styles?

File: tmt-app/src/Components/Quiz.jsx [hunk 4]
```diff
@@ -29,6 +28,27 @@ function Quiz() {
...
+            backgroundColor: 'Matcha.main',
+            '&.MuiButtonBase-root': {
+              padding: {
+                xs: '1rem 2.5rem',
+                xl: '1rem 3.25rem',
+              },
+            },
+          }}
+        >
+          <Typography variant="h4">Next</Typography>
```
Comment (jwu910) [inline tmt-app/src/Components/Quiz.jsx:49]: I don't think this should be an h4 variant, button text isn't normally a heading. And as a habit we shouldn't get used to treating and using heading elements just for sizing

**Review by jwu910 — CHANGES_REQUESTED** [review]
Is there a ticket this is connected to? Can we reference it in the description?

**Comment by Raymond0T** [comment]
> Is there a ticket this is connected to? Can we reference it in the description?
we didn't have a ticket for it before but it is referenced now

File: tmt-app/src/Components/Quiz.jsx (hunk 1 above)
Comment (Raymond0T) [reply tmt-app/src/Components/Quiz.jsx:31]: This was going to be a temporary button to navigate through the quiz without having to change url. I will make the adjustment to make it the permanent now.

Comment (jwu910) [reply tmt-app/src/Components/Quiz.jsx:31]: Sounds good, yeah if we're gonna add a temp button might as well put in the few extra steps for the one matching the design spec

File: tmt-app/src/Components/Quiz.jsx (hunk 3 above)
Comment (Raymond0T) [reply tmt-app/src/Components/Quiz.jsx]: This button was re-used from our previous components. I also believe the styling for the button size variants are different than our design.

File: tmt-app/src/Components/Quiz.jsx (hunk 4 above)
Comment (Raymond0T) [reply tmt-app/src/Components/Quiz.jsx]: Our custom h4 variant matches the style we need for this button. Should I create another variant just for buttons?

Comment (jwu910) [reply tmt-app/src/Components/Quiz.jsx]: I dont think we need another variant we can just leave the text here, and let the button style it. Buttons can apply text styling as well. and we can consider the primary/secondary button variants per the design spec

**Review by jwu910 — CHANGES_REQUESTED** [review]
can you take a look at the figma again?

https://www.figma.com/file/s7breBLT582LXnYvfU8FAW/BobaTalks-Major-Picker?type=design&node-id=1379-43047&mode=dev

button interactions are missing from the current implementation

Also the back button takes you forward

File: tmt-app/src/Components/QuizButtonContainer.jsx [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+              border: '3px solid #732C2C',
+            },
+          }}
+        >
+          <Typography variant="h4" sx={{ visibility: 'hidden' }}>
+            {step === 'classes' ? 'Next Question' : "I'm Finished"}
+          </Typography>
+          <Typography variant="h4" sx={{ position: 'absolute' }}>
+            Back
+          </Typography>
```
Comment (jwu910) [inline tmt-app/src/Components/QuizButtonContainer.jsx:43]: What was your reason for choosing two Typography elements like this?

File: tmt-app/src/Components/QuizButtonContainer.jsx [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+            backgroundColor: 'white',
+            color: 'Matcha.main',
+            border: '3px solid #73956F',
+            padding: {
+              xs: '1rem 1.75rem',
+              md: '1.25rem 4.25rem',
+            },
+            '&:hover': {
+              color: 'white',
+              border: '3px solid #732C2C',
```
Comment (jwu910) [inline tmt-app/src/Components/QuizButtonContainer.jsx:34]: We should use color variables instead of hard coding hex codes

File: tmt-app/src/Components/QuizButtonContainer.jsx (hunk 5 above)
Comment (jwu910) [reply tmt-app/src/Components/QuizButtonContainer.jsx:43]: image

Populating the dom with multiple elements like this can create accessibility issues and is discouraged. Read up on the nuances of `visibility: hidden` as well too. Using react, we have access to much more robust logic that can help produce a very clean DOM and not have to play with CSS

File: tmt-app/src/Components/QuizButtonContainer.jsx [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+            },
+          }}
+        >
+          <Typography variant="h4" sx={{ visibility: 'hidden' }}>
+            {step === 'classes' ? 'Next Question' : "I'm Finished"}
```
Comment (jwu910) [inline tmt-app/src/Components/QuizButtonContainer.jsx:39]: You've got mixed single and double quotes here, as well. did we lose the linter? @michachan

**Review by jwu910 — CHANGES_REQUESTED** [review]

**Comment by jwu910** [comment]
image


also per the designers

File: tmt-app/src/Components/QuizButtonContainer.jsx (hunk 5 above)
Comment (Raymond0T) [reply tmt-app/src/Components/QuizButtonContainer.jsx:43]: This is my bad, I forgot about accessibility. This was to create equal size buttons without having to set width.

**Comment by Raymond0T** [comment]
> image
> 
> also per the designers

This would be done in another PR when we fix maximum card selected issue and also saving user's selection.

**Comment by jwu910** [comment]
> 
> This would be done in another PR when we fix maximum card selected issue and also saving user's selection.

Sure that's fine. Was there a ticket already for that too?

**Review by michachan — APPROVED** [review]
